updated data-storage-impl-s3 Test Files
adorsys/datasafe pull request #299
Opened 2024-04-11 12:07 UTC by AssahBismarkabah

update Test Files in data-storage-impl-s3 Module

2024-04-11 12:08 UTC, AssahBismarkabah commented
hello sir @francis-pouatcha please review this PR

2024-04-12 08:28 UTC, francis-pouatcha commented
Synchronized you branch with develop so you can have use the -PIT to test activation of integration tests: https://github.com/adorsys/datasafe/pull/306

Please merge the pull request and test again.

2024-04-12 08:28 UTC, francis-pouatcha requested changes
Please merge: https://github.com/adorsys/datasafe/pull/306 and test again.

2024-04-13 06:40 UTC, francis-pouatcha approved these changes

2024-04-13 06:40 UTC, merged