Rename datasafe simple adapter spring test files
adorsys/datasafe pull request #330
Opened 2024-07-09 15:20 UTC by AssahBismarkabah

2024-07-10 07:55 UTC, Thendo20 approved these changes
@AssahBismarkabah It looks good to me

2024-07-10 08:10 UTC, max402 requested changes
SimpleDatasafeAdapterTest this test uses minio docker image and quite heavy. So should be IT

2024-07-10 08:10 UTC, max402 commented on datasafe-simple-adapter/datasafe-simple-adapter-impl/src/test/java/de/adorsys/datasafe/simple/adapter/impl/SimpleAdapterFeatureIT.java
> +class SimpleAdapterFeatureIT extends BaseMockitoTest {
This class doesn't use docker and works quite fast.

2024-07-10 08:10 UTC, max402 commented on datasafe-simple-adapter/datasafe-simple-adapter-spring/src/test/java/de/adorsys/datasafe/simple/adapter/spring/InjectionForFilesystemIT.java
> +public class InjectionForFilesystemIT extends InjectionIT {
it's a simple test

2024-07-10 09:54 UTC, AssahBismarkabah commented
updated @max402

2024-07-15 08:22 UTC, max402 approved these changes

2024-07-15 08:22 UTC, max402 commented on datasafe-simple-adapter/datasafe-simple-adapter-impl/src/test/java/de/adorsys/datasafe/simple/adapter/impl/SimpleAdapterFeatureTest.java
> +
make sure that classes remain untouched when undoing changes

2024-07-15 09:04 UTC, merged