Fix: ensure unique iv generation for GCM encryption to prevent reuse error
adorsys/datasafe pull request #344
Opened 2024-08-05 11:29 UTC by AssahBismarkabah

Added `SecureRandom` to JceCMSContentEncryptorBuilder in CMSEncryptionServiceImpl to ensure unique IV generation for each encryption operation.

2024-08-08 08:08 UTC, francis-pouatcha requested changes

2024-08-08 08:08 UTC, francis-pouatcha commented on datasafe-encryption/datasafe-encryption-impl/src/main/java/de/adorsys/datasafe/encrypiton/impl/cmsencryption/CMSEncryptionServiceImpl.java
> +                new JceCMSContentEncryptorBuilder(algorithm).setProvider(GeneratorModule_ProviderFactory.provider()).setSecureRandom(new SecureRandom()).build()
What about instantiating SecureRandom() once in the object, and passing it toeach encryptor?

2024-08-12 07:17 UTC, AssahBismarkabah commented
resolved @francis-pouatcha

2024-08-13 08:22 UTC, francis-pouatcha approved these changes

2024-08-13 08:24 UTC, merged