DOC-194 Example with versioning and how it works.
adorsys/datasafe pull request #353
Opened 2024-09-25 12:49 UTC by Motouom

2024-10-01 15:55 UTC, AssahBismarkabah reviewed
hello @Motouom 
i guess this doc on example with versioning has been described already in the https://github.com/adorsys/datasafe/blob/develop/docs/readme/HowItWorks.md you could include the modifications directly and add the test for the example with unencrypted path

2024-10-04 12:29 UTC, Motouom commented
> hello @Motouom i guess this doc on example with versioning has been described already in the https://github.com/adorsys/datasafe/blob/develop/docs/readme/HowItWorks.md you could include the modifications directly and add the test for the example with unencrypted path

@AssahBismarkabah that documentation provides an overview of the Datasafe project, but when going specific mise, I prefer to do it in a different file, since it describes something specific.

2024-10-04 13:54 UTC, AssahBismarkabah requested changes
ok @Motouom  then just include the example with `unencrpted path` as it is included in the documentation

2024-10-10 12:03 UTC, AssahBismarkabah approved these changes

2024-10-15 08:03 UTC, merged